initial shopping list part 5
javaGuruBY/jis8_homework pull request #108
Opened 2021-10-02 13:16 UTC by KaydunovDenis

this is copy part 4 for update to part 5

2021-10-02 17:02 UTC, trump-ny approved these changes, later dismissed

2021-10-04 20:35 UTC, Puzzletania approved these changes, later dismissed

2021-10-05 09:31 UTC, max-java requested changes
ptal

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/main/java/github/kaydunovdenis/service/product_validator/ProductNameValidator.java
> +                && isNameUnique(product);
было бы хорошо иметь отдельные валидаторы которые возвращают результать валидации, а рутовый валидатор возвращает коллекцию результатов

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/bean/product/ProductTest.java
> +        Assert.assertEquals(0, product.getId().compareTo(expect));
здесь должен отработать assertEquals(product1, product2)

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/bean/product/ProductTest.java
> +        LOG.info("Result:\n {}", product);
junit выводит в лог значения для сравнения, если они отличаются.

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/repository/ProductRepositoryHashMapTest.java
> +        Assert.assertEquals(0, ProductRepositoryHashMap.getProductMap().size());
это отдельные тесты
productMapShouldBeInitailizedOnStart
productMapShouldBeEmptyOnStart

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/repository/ShoppingCartRepositoryTest.java
> +    public void saveShoppingCart() {
ты сделал зависимость между тестами, так делать категорически нельзя

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/repository/ShoppingCartRepositoryTest.java
> +        shoppingCartRepository.removeShoppingCart(testShoppingCart);
данные должны быть подготовлены для теста перед removeShoppingCart
тогда это будет юнит тест. 

Сейчас ты создаешь и удаляешь одним и тем же инструментом, который и тестируешь

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/service/ProductServiceTest.java
> +        ProductService.getPercentageDiscount(product);
для того, что бы коллегам было понятно что ты тестируешь, рекомендуется юнит тесты называть 
whenDiscountOver100_shouldReturnNoMoreThan100()

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/service/ProductServiceTest.java
> +        var product = ProductTest.getDefaultProduct();
Это лучше вынести в отдельный класс типа TestProductsProvider

2021-10-05 09:31 UTC, max-java commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/service/product_validator/DiscountValidatorTest.java
> +        checkNotAvailableDiscount();
это отдельные тесты. 
Если ты хочешь их объединить по какому-то признаку, посмотри https://www.baeldung.com/junit-5#test-suites

2021-10-05 12:58 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/main/java/github/kaydunovdenis/ShoppingListApplication.java
> +        shoppingCartService.addProduct(shoppingCart2, product4);
Будет пофикшено при при обновлении в следующей части задачи. Это перенесено в тесты и использован Spring.

2021-10-05 13:11 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/bean/product/ProductTest.java
> +        Assert.assertEquals(0, product.getId().compareTo(expect));
@max-java а где взять другой продукт?
Мы ведь просто проверяем что ID изменился на необходимый.

2021-10-05 13:11 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/bean/product/ProductTest.java
> +        LOG.info("Result:\n {}", product);
fixed

2021-10-05 13:16 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/repository/ProductRepositoryHashMapTest.java
> +        Assert.assertEquals(0, ProductRepositoryHashMap.getProductMap().size());
fixed

2021-10-08 06:26 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/main/java/github/kaydunovdenis/service/product_validator/ProductNameValidator.java
> +                && isNameUnique(product);
Валидаторы сделал как void.
В случае не прохождение валидации бросается ProductValidationException
Валидаторы объединены под общий интерфейс.

2021-10-08 07:12 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/service/product_validator/DiscountValidatorTest.java
> +        checkNotAvailableDiscount();
Таким способом я хотел обозначить какой метод они тестируют

2021-10-12 07:19 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/repository/ShoppingCartRepositoryTest.java
> +        shoppingCartRepository.removeShoppingCart(testShoppingCart);
Я не понимаю как нужно это написать..

2021-10-12 07:26 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/test/java/github/kaydunovdenis/repository/ShoppingCartRepositoryTest.java
> +    public void saveShoppingCart() {
@max-java Не понимаю, где здесь зависимость и между какими тестами, можешь объяснить?

2021-10-27 14:56 UTC, PavelBoPavel submitted a review, later dismissed

2021-10-27 15:21 UTC, VasiliZas submitted a review, later dismissed

2021-12-20 08:41 UTC, KaydunovDenis commented on homework/kaydunov_denis/shopping_list_application_part5/src/main/java/github/kaydunovdenis/ShoppingListApplication.java
> +        shoppingCartService.addProduct(shoppingCart2, product4);
Все верно. Вся необоходимая инициализация перенесена в класс SpringConfig. 
Инициализация сущностей Product, ShoppingCartService, ShoppingCart здесь вообще не нужна, все это вынесено в тесты.

2023-05-15 05:52 UTC, closed without merging