car task
javaGuruBY/jis8_homework pull request #18
Opened 2021-07-06 19:08 UTC by VasiliZas

2021-07-08 12:41 UTC, lamaconda approved these changes
lgfm, but don't forget about adding empty line in the end of code

2021-07-15 09:40 UTC, max-java requested changes
please, add some tests and run sonarQube analyse

2021-07-15 09:40 UTC, max-java commented on homework/Vasili_Zasinets/hw1/CarDemo.java
> +    boolean result;
result of what? Please, give meaningful name to the variable.

2021-07-15 09:40 UTC, max-java commented on homework/Vasili_Zasinets/hw1/CarDemo.java
> +    };
```
if (car.getCurentSpeed() > 0) {
            return true;
        }
        return false;
```

2021-07-15 09:40 UTC, max-java commented on homework/Vasili_Zasinets/hw1/CarDemo.java
> +            }
this looks like check that could be encapsulate into  method with meaningful name

2021-07-15 09:40 UTC, max-java commented on homework/Vasili_Zasinets/hw1/CarDemo.java
> +                newSpeed = car.getMaxSpeed();
this looks like check that could be encapsulate into method with meaningful name

2021-07-16 16:30 UTC, closed without merging