VasiliZas
javaGuruBY/jis8_homework pull request #21
Opened 2021-07-10 19:20 UTC by VasiliZas

2021-07-12 20:03 UTC, trump-ny submitted a review, later dismissed

2021-07-12 20:46 UTC, lamaconda requested changes

2021-07-12 20:46 UTC, lamaconda commented on homework/Vasili_Zasinets/hw0709/decoder/Encoder.java
> +        System.out.println("code = " + code);
better use logger

2021-07-15 09:47 UTC, max-java requested changes
please, use quickstart template and run sonarQube analyse before pull request

2021-07-15 09:47 UTC, max-java commented on homework/Vasili_Zasinets/hw0709/decoder/EncoderDemo.java
> +    }
This should be moved to tests

2021-07-15 09:47 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/Butterfly.java
> +            for (i = 0; i < butterfly.length; i++) {
```
for (int k = 0; k < butterfly.length; k++) {
            for (int i = 0; i < butterfly.length; i++) {
```

2021-07-15 09:47 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/Butterfly.java
> +                System.out.print(butterfly[k][i]);
logger should be used

2021-07-15 09:47 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/Butterfly.java
> +        int i;
looks like test case, should be moved to tests

2021-07-16 19:48 UTC, closed without merging