Look array service
javaGuruBY/jis8_homework pull request #25
Opened 2021-07-14 18:39 UTC by VasiliZas

Look array service

2021-07-14 18:55 UTC, PavelBoPavel approved these changes
+

2021-07-15 08:56 UTC, max-java requested changes
Technically fine, but I insist that you should use quickStart example and sonarQube code verification

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0709/decoder/Encoder.java
> +        log.info("code = " + code);
It's preferable to use 
```
log.info("code = {} ", code);
```

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0709/decoder/Encoder.java
> +        log.info("symbol = " + symbol);
see comment above

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0709/decoder/EncoderDemo.java
> +    }
This should be moved to tests

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/Butterfly.java
> +            System.out.println();
1. use logger
2. 
```
for (int k = 0; k < butterfly.length; k++) {
            for (int i = 0; i < butterfly.length; i++) {
```

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/Butterfly.java
> +        int k;
this declaration is redundunt

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/LookupArrayService.java
> +    int indexMax = -1;
Please, make equal indentation

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/LookupArrayService.java
> +    return i;}
please, run style checking

2021-07-15 08:56 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/LookupArrayServiceTest.java
> +        this.i = 5;
this declarations are redundant. Expected simple values could be hardcoded right in the test, it's ok. Otherwise, fabric method could be used.

2021-07-15 22:56 UTC, KaydunovDenis approved these changes

2021-07-16 18:51 UTC, trump-ny approved these changes

2021-07-16 19:57 UTC, closed without merging