Names and Types variable
javaGuruBY/jis8_homework pull request #27
Opened 2021-07-14 20:55 UTC by PavelBoPavel

2021-07-15 07:19 UTC, lamaconda submitted a review, later dismissed
lgfm

2021-07-15 08:41 UTC, max-java requested changes
Technically looks good, but I insist that you should use quick start template and sonarCube analyse. 
Please, make appropriate changes and add tests.

2021-07-15 08:41 UTC, max-java commented on homework/PavelBo/dataTypes/encoder/src/main/java/com/github/pavelbopavel/EncoderDemo.java
> +}
this should be moved to test

2021-07-15 08:41 UTC, max-java commented on homework/PavelBo/dataTypes/nameVariables/src/main/java/com/github/PavelBoPavel/bean/TypesVariable.java
> +    private boolean hungryMan;
isHungry will be more more obvious

2021-07-15 22:49 UTC, KaydunovDenis approved these changes

2021-07-15 22:49 UTC, KaydunovDenis commented on homework/PavelBo/dataTypes/nameVariables/src/main/java/com/github/PavelBoPavel/bean/NamesVariable.java
> +    private int speedCar;
carSpeed

2021-07-16 14:43 UTC, trump-ny submitted a review, later dismissed

2021-07-16 15:02 UTC, Puzzletania submitted a review, later dismissed

2021-07-20 11:23 UTC, lamaconda approved these changes
lgfm

2021-07-20 16:18 UTC, VasiliZas approved these changes

2021-07-21 08:48 UTC, lamaconda approved these changes
lgfm

2021-07-21 08:48 UTC, lamaconda commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Book.java
> +}
Я бы сделал первым конструктор, потом геттеры сеттеры, потом equals and hash code, и в конце ту стринг

2021-07-21 08:48 UTC, lamaconda commented on homework/PavelBo/collections/library/src/test/java/com/tutrit/java/quickstart/LibraryTest.java
> +    }
необходимо ли всё это делать перед каждым тестом?

2021-07-22 10:55 UTC, KaydunovDenis submitted a review, later dismissed

2021-07-22 15:00 UTC, PavelBoPavel commented on homework/PavelBo/collections/library/src/test/java/com/tutrit/java/quickstart/LibraryTest.java
> +    }
да. Это используется каждый раз

2021-07-25 17:55 UTC, PavelBoPavel commented on homework/PavelBo/dataTypes/encoder/src/main/java/com/github/pavelbopavel/EncoderDemo.java
> +}
так и сделал, чуть ниже в комите "@PavelBoPavel
refactoring encoder. Add test"

2021-07-27 11:22 UTC, max-java requested changes
ptal

Please, one merge request for one task

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/stringTokenizer/src/main/java/com/tutrit/java/quickstart/StringAnalyzer.java
> +}
this looks complicated. Could you please split this into separate method that could be tested independently?

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/stringTokenizer/src/test/java/com/tutrit/java/quickstart/StringAnalyzerTest.java
> +public class StringAnalyzerTest extends TestCase {
use jUnit4 or 5

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/stringTokenizer/src/test/java/com/tutrit/java/quickstart/StringAnalyzerTest.java
> +        Assert.assertEquals(17, sentences.size());
Bp is to use static imports for Assert methods

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/stringTokenizer/src/test/java/com/tutrit/java/quickstart/StringAnalyzerTest.java
> +        List<String> words = stringAnalyzer.splitToWords(Text.text);
It's better not to use production data in unit tests, but simple data that obviously shows that method works. Replace Text.text with something simple

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/word vocabulary/src/main/java/com/github/pavelbopavel/UniqueWordVocabulary.java
> +        }
```
if(!word.equals("")) {
  words.add(word);
}
```

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/word vocabulary/src/main/java/com/github/pavelbopavel/UniqueWordVocabulary.java
> +        uniqueWordVocabulary.words.add("cat");
try Set.of()

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/word vocabulary/src/main/java/com/github/pavelbopavel/UniqueWordVocabulary.java
> +
That should be moved in test!

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/wordCounter/src/test/java/com/tutrit/java/quickstart/UniqueWordCounterTest.java
> +import static org.junit.Assert.*;
you'd better avoid of use * in imports

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/collections/wordCounter/src/test/java/com/tutrit/java/quickstart/UniqueWordCounterTest.java
> +    }
you should add at least 1 assertion

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/dataTypes/encoder/src/test/java/com/github/pavelbopavel/EncoderTest.java
> +        encoder.encoder(code);
you should have at lease 1 assertion

for that, you should return a value )

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/dataTypes/wrappers/src/test/java/com/github/pavelbopavel/WrapperDemoTest.java
> +        log = LoggerFactory.getLogger(WrapperDemoTest.class);
I don't think we want to logger will be created for every test, do we?

2021-07-27 11:22 UTC, max-java commented on homework/PavelBo/dataTypes/wrappers/src/test/java/com/github/pavelbopavel/WrapperDemoTest.java
> +        Assert.assertEquals(i1.hashCode(), i2.hashCode());
that is not how immutability tests. 
When you test if object hasn't been mutate, you should prove that it's original value did not changed. Revise your test

2021-07-28 18:49 UTC, VasiliZas approved these changes

2021-07-29 12:51 UTC, closed without merging