yaroslav_zhimanov
javaGuruBY/jis8_homework pull request #29
Opened 2021-07-16 15:02 UTC by trump-ny

2021-07-22 10:46 UTC, KaydunovDenis requested changes

2021-07-22 10:46 UTC, KaydunovDenis commented on homework/yaroslav_zhimanov/array/butterfly/Butterfly.java
> +                //Логгер не до конца понимаю. Разберусь, тогда буду писать логгер.
Don't create pull request if you don't finiched task.
See the cod other students about logger.

2021-07-22 10:46 UTC, KaydunovDenis commented on homework/yaroslav_zhimanov/array/min_max/MinMax.java
> +
delete empty lines

2021-07-27 11:35 UTC, max-java requested changes
Please, use quickstart project and sonar verification.

2021-07-27 11:35 UTC, max-java commented on homework/yaroslav_zhimanov/array/min_max/MinMax.java
> +    public static void main(String args[]) {
we do not use main method for testing purposes.
Please, use tests for that.

2021-07-27 11:35 UTC, max-java commented on homework/yaroslav_zhimanov/random_generator/RandomGeneratorDemo.java
> +class RandomGeneratorDemo {
Please, use tests instead of demo

2021-07-27 11:35 UTC, max-java commented on homework/yaroslav_zhimanov/random_generator/RandomGeneratorDemo.java
> +        System.out.println("Случайное число 2: " + randomb);
this comment is redundant.

2021-08-14 18:58 UTC, closed without merging