how use main method
javaGuruBY/jis8_homework pull request #31
Opened 2021-07-16 18:58 UTC by max-java

2021-07-22 09:48 UTC, KaydunovDenis commented
I don't understand your question.

2021-07-23 10:27 UTC, KaydunovDenis requested changes
Не понимаю суть твоего вопроса.

2021-07-27 11:39 UTC, max-java commented
> Не понимаю суть твоего вопроса.

Than you'd better be on lecture )

2021-07-27 12:10 UTC, KaydunovDenis submitted a review, later dismissed
Where is the task description?

See my comment.

2021-07-27 12:10 UTC, KaydunovDenis commented on lecturer/716_operators/src/main/java/com/tutrit/java/quickstart/Application.java
> +                    break;
Situation with lenght = 2 don't will you check?

2021-07-27 12:10 UTC, KaydunovDenis commented on lecturer/716_operators/src/test/java/com/tutrit/java/quickstart/ApplicationTest.java
> +    }
Need realisation. I think it Maks want show on lecture.

2021-07-27 12:10 UTC, KaydunovDenis commented on lecturer/716_operators/src/test/java/com/tutrit/java/quickstart/ApplicationTest.java
> +
unnecessary blank line

2021-07-27 12:10 UTC, KaydunovDenis commented on lecturer/716_operators/src/main/java/com/tutrit/java/quickstart/Application.java
> +    private void propertiesExample(String[] args) {
What is this method?
I don't can find where it using.

2021-07-28 09:11 UTC, VasiliZas approved these changes

2021-07-30 10:09 UTC, KaydunovDenis approved these changes

2021-08-04 16:04 UTC, PavelBoPavel approved these changes

2021-08-04 16:04 UTC, merged