My all Task
javaGuruBY/jis8_homework pull request #33
Opened 2021-07-18 09:54 UTC by VasiliZas

My all Task. I had some problems with IDea and branches, I had to make a new branch with all the tasks.

2021-07-18 10:06 UTC, PavelBoPavel approved these changes
+

2021-07-19 12:45 UTC, PavelBoPavel approved these changes
+

2021-07-22 09:45 UTC, KaydunovDenis commented
Ask Mask your qustion on lecture.

2021-07-27 11:57 UTC, max-java requested changes
In general looks good, I've got minors comments according to production best practices. 
Nevertheless, please:
1. use quickstart project for every task
2. run sonarqube verification
3. make one mergeRequest per task

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/src/main/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0713/Butterfly.java
> +        }
main method is neither for demo nor for tests. Please, move this code where it should be

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/src/main/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0713/LookupArrayService.java
> +    int indexMax = -1;
I guess logic should works that way in witch these vars are redundant.

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/src/main/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0713/LookupArrayService.java
> +        arrayMax = array[0];
yep, you could just have 
```
int arrayMax = array[0];
```

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/src/main/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0713/NumberService.java
> +    int summForSmall(int start, int finish) {
I don't get it, what do you mean by sum for small?

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/src/main/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0713/NumberService.java
> +    int selectionForEven(int start, int finish) {
Please, consider self-explanatory names for methods.

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0718/src/main/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0718/ArrayService.java
> +        }
this verification could be encapsulated in separate method

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0718/src/test/java/com/tutrit/java/quickstart/homework/Vasili_Zasinets/hw0718/ArrayServiceTest.java
> +
I don't see any service calls here... Should you test it?

2021-07-27 11:57 UTC, max-java commented on homework/Vasili_Zasinets/hw0713/src/test/java/com/tutrit/java/quickstart/hw0713/LookupArrayServiceTest.java
> +    int i;
this don't belong here. It's could be move in tests according it's purposes.

2021-07-27 19:48 UTC, closed without merging