Add files via upload
javaGuruBY/jis8_homework pull request #4
Opened 2021-07-01 18:38 UTC by VasiliZas

Task about Numbers

2021-07-02 16:25 UTC, lamaconda commented on hw2/NumberServiceTest.java
> +}
В конце должна оставаться пустая строчка

2021-07-02 16:27 UTC, javaGuruBY requested changes
PTAL, and please use maven quickstart project and sonar scanner.

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberService.java
> +                result = start + result;
At this point if result already has value, it'll be used. Should you reset it?

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberService.java
> +                start = start - 1;
encapsulate this into single mehtod

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberService.java
> +        if (start > finish) {
if () else () encapsulate to another single method.

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberService.java
> +                result = start + result;
result =+ start

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberService.java
> +    public static int result;
this variable is redundunt

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberService.java
> +    public int rangeEvenCount(int start, int finish) {
all the same as for result and method above

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberServiceTest.java
> +import static org.junit.Assert.*;
Use Ctrl+Alt+O to optimize imports

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberServiceTest.java
> +int exp2;
not used, delete it.

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberServiceTest.java
> +}
add new line in the end of the file

2021-07-02 16:27 UTC, javaGuruBY commented on hw2/NumberServiceTest.java
> +NumberService numberService = new NumberService();
```
NumberService numberService;

@Before
public void setUp() {
    numberService = new NumberService();
}
```

2021-07-02 16:27 UTC, lamaconda commented on hw2/NumberService.java
> +}
В конце пустая строчка

2021-07-02 16:29 UTC, lamaconda requested changes
add empty line in the end of programm

2021-07-05 12:50 UTC, lamaconda approved these changes
lgfm, but you should add new line in the end of the file

2021-07-06 18:45 UTC, closed without merging