finished butterfly task, please review
javaGuruBY/jis8_homework pull request #40
Opened 2021-07-19 15:42 UTC by lamaconda

2021-07-19 17:19 UTC, Puzzletania approved these changes

2021-07-19 17:34 UTC, VasiliZas approved these changes

2021-07-19 19:20 UTC, PavelBoPavel approved these changes
+

2021-07-20 15:32 UTC, trump-ny approved these changes

2021-07-22 09:09 UTC, KaydunovDenis approved these changes

2021-07-27 13:03 UTC, max-java requested changes
It's not how it should work, but it's deferentially will. ))

You need to create an algorithm that prints a butterfly of any size.

2021-07-29 12:13 UTC, KaydunovDenis requested changes

2021-07-29 12:13 UTC, KaydunovDenis commented on homework/shelkovich_ilya/butterfly/src/main/java/com/tutrit/java/quickstart/Application.java
> +        };
Так не подходит.
Массив должен заполняться как бабочка. 
А его размеры должны определяться входящими аргументами.

This is not true.
The array should be fill like a butterfly.
And its size should be determined by the input arguments.

2021-09-03 13:48 UTC, closed without merging