RandomGeneratorDemo
javaGuruBY/jis8_homework pull request #42
Opened 2021-07-20 10:43 UTC by trump-ny

2021-07-20 12:37 UTC, VasiliZas approved these changes

2021-07-21 06:12 UTC, PavelBoPavel approved these changes

2021-07-21 06:12 UTC, PavelBoPavel commented on random_generator/RandomGeneratorDemo.java
> +        Integer randoma = random.nextInt(1000);
я бы именовал переменные следующим образом : randomA, randomB, randomC

2021-07-21 06:12 UTC, PavelBoPavel commented on random_generator/RandomGeneratorDemo.java
> +        for (c = 1; c <= 1; c++) ;
для чего эти циклы?

2021-07-22 07:55 UTC, KaydunovDenis reviewed
Если бы было описание таски, было бы проще делать ревью кода

2021-07-22 07:57 UTC, KaydunovDenis requested changes

2021-07-22 07:57 UTC, KaydunovDenis commented on random_generator/RandomGeneratorDemo.java
> +        Integer randoma = random.nextInt(1000);
use camelCase in naming

2021-07-22 07:57 UTC, KaydunovDenis commented on random_generator/RandomGeneratorDemo.java
> +        Integer summa = randoma + randomb + randomc;
summa -> sum

2021-07-27 12:58 UTC, max-java requested changes
use quckstart project and sonar verification, please.
write tests to prove code works instead of messing with main() method.

2021-07-27 12:58 UTC, max-java commented on random_generator/RandomGeneratorDemo.java
> +        System.out.println("Случайное число 3: " + randomc);
I guess I've already saw this comment. 
Isn't it duplicate?

2021-08-14 18:59 UTC, closed without merging