UserService
javaGuruBY/jis8_homework pull request #49
Opened 2021-07-22 19:24 UTC by PavelBoPavel

2021-07-22 20:23 UTC, trump-ny approved these changes

2021-07-23 08:52 UTC, VasiliZas approved these changes

2021-07-23 10:17 UTC, KaydunovDenis requested changes

2021-07-23 10:17 UTC, KaydunovDenis commented on homework/PavelBo/loops/userLoginService/src/main/java/com/tutrit/java/quickstart/User.java
> +    private boolean BLOCKED;
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

BLOCKED -> isBlocked
переменная пишется заглавными буквами когда она
The names of variables declared class con-stants  and of ANSI constants should be alluppercase with words separated by under-scores (“_”). (ANSI constants should beavoided, for ease of debugging.)
-> public static final

2021-07-23 10:17 UTC, KaydunovDenis commented on homework/PavelBo/loops/userLoginService/src/main/java/com/tutrit/java/quickstart/User.java
> +    }
move duwn this methods and add toString

2021-07-23 10:17 UTC, KaydunovDenis commented on homework/PavelBo/loops/userLoginService/src/main/java/com/tutrit/java/quickstart/User.java
> +}
move up this methods

2021-07-23 10:17 UTC, KaydunovDenis commented on homework/PavelBo/loops/userLoginService/src/main/java/com/tutrit/java/quickstart/UserLoginService.java
> +    User user;
make private

2021-08-14 10:11 UTC, max-java requested changes
ptal, and see colleagues comments.

2021-08-14 10:11 UTC, max-java commented on homework/PavelBo/loops/userLoginService/src/test/java/com/tutrit/java/quickstart/UserLoginServiceTest.java
> +}
please, add empty row

2021-08-14 10:11 UTC, max-java commented on homework/PavelBo/loops/userLoginService/src/main/java/com/tutrit/java/quickstart/UserLoginService.java
> +                blockedUser(user);
`blockedUser(user);` -> `blockUser(user);`will be more readable

also, I suggest that you use Atl+Ctrl +L before merge

2021-08-14 10:11 UTC, max-java commented on homework/PavelBo/loops/userLoginService/src/main/java/com/tutrit/java/quickstart/UserLoginService.java
> +    private boolean isPassword(User user, String password) {
`isPassword` -> `verifyPassword` more readable

2021-08-17 11:12 UTC, closed without merging