Task Prime Numbers
javaGuruBY/jis8_homework pull request #50
Opened 2021-07-22 20:42 UTC by trump-ny

2021-07-22 20:52 UTC, trump-ny commented
PLEASE SEE TASK PRIME NUMBERS!!!!     TASKS Array Butterfly, MinMaxValue in Array ,RandomGeneratorDemo DON'T LOOK....  Accidentally added in commit.

2021-07-23 08:57 UTC, VasiliZas approved these changes

2021-07-23 10:24 UTC, KaydunovDenis approved these changes

2021-07-23 10:24 UTC, KaydunovDenis commented on homework/yaroslav_zhimanov/for_homework/PrimeNumbers.java
> +
delete empty lines

2021-07-25 18:04 UTC, PavelBoPavel approved these changes

2021-08-14 11:14 UTC, max-java requested changes
Slit this into projects, separate for each one task.
Add quickstart project, and use sonar.

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/array/butterfly/Butterfly.java
> +            System.out.println(" ");
You'd better start adding logger right now. 
Do not hesitate to ask questions in lectures if you don't understand smth. 
It is very important to not to study alone or put off important materials for later

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/array/min_max/MinMax.java
> +
Move this into tests

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/array/min_max/MinMax.java
> +
remove empty rows

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/array/min_max/MinMax.java
> +
remove empty rows

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/for_homework/PrimeNumbers.java
> +package for_homework;
you'd better not use underscore in package names. 
Use Sonar

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/for_homework/PrimeNumbers.java
> +        System.out.print(sumWithout17and71);
encapsulate this into Class and Method

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/for_homework/PrimeNumbers.java
> +        int sumWithout17and71=0;
This looks like test case, move this to tests.

2021-08-14 11:14 UTC, max-java commented on homework/yaroslav_zhimanov/random_generator/RandomGeneratorDemo.java
> +        System.out.println("Сумма всех сгенерированных чисел: " + summa);
Divide this into service and test cases

2021-08-14 19:00 UTC, closed without merging