[WIP ]Exceptions
javaGuruBY/jis8_homework pull request #57
Opened 2021-07-26 16:11 UTC by PavelBoPavel

1. Напишите метод, который потенциально может выбросить ArrayIndexOutOfBoundException. Напишите тест, из которого очевидно при каких исходных условиях  этот метод может пробросить exception

2. Тоже самое для NullPointerException

3. Создайте свой ексепшн (А), унаследовавшись от класса Exception, и переиспользуя все родительские конструкторы. Создайте свой ексепшн (B), унаследовавшись от класса А. Напишите метод risky(), который может потенциально может выбросить ексепшн B, и напишите метод safety(), в котором отловите ексепшн B и пробросьте ексепшн А. Напишите тесты, из которых очевидно при каких исходных условиях  этоти методы могут пробрасывать exception. Напишите тест, в котором метод risky() бросает NullPointerException. Подумайте, какие при этом есть способы сохранить работоспособность программы.

4. Повторите тоже самое, но наследуясь от класса RuntimeException. Не копируйте созданное в пункте 3, а перепишите заново, обращая внимание на разницу поведения компилятора в случае, если не указывать блоки try/catch.

5*. Повторите упражнение п.3, но в этот раз создайте иерархию классов А -> B -> C. В конструкторе класса С вызовите конструктор класса B, в конструкторе класса B вызовите конструктор класса A. Создайте ситуацию, при которой в каждом из конструкторов может быть выброшен Exception, и отловите его в блоке try/catch. Покажите, что конструктор наследуемого класса не может ловить исключения, брошенные конструктором родительского класса.

6*. Используя цикл while сделайте возобновляемой работу метода , который пробрасывает exception, до тех пор, пока exception больше не будет выбрасываться.

2021-08-04 17:52 UTC, VasiliZas approved these changes

2021-08-05 12:07 UTC, KaydunovDenis requested changes

2021-08-05 12:07 UTC, KaydunovDenis commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    public void arrayIndexOutOfBound(int i){
I don't like name these method. Maybe it seems to me. I don't sure, but I can 
call your attention on it.

2021-08-05 12:07 UTC, KaydunovDenis commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    public void nullPointer(){
Same thing here.
Need use the  verb in the name.

2021-08-05 12:07 UTC, KaydunovDenis commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    public void riskyNullPointer(String value) throws NullPointerException {
Same thing here.
Need use the verb in the name.

2021-08-05 12:07 UTC, KaydunovDenis commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    public int riskyLastValueZero(int[] values) throws ArrayLastValueZeroException {
Same thing here.
Need use the verb in the name.

2021-08-05 12:07 UTC, KaydunovDenis commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    public int safetyOddValue(int[] values) throws ArrayOddValueException {
Same thing here.
Need use the verb in the name. Etcetera.

2021-08-05 12:07 UTC, KaydunovDenis commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    }
What is it?

2021-08-06 08:17 UTC, PavelBoPavel commented on homework/PavelBo/exceptions/knowingExceptions/src/test/java/com/tutrit/java/quickstart/service/VerificationTest.java
> +    Verification verification;
в тесте???

2021-08-06 08:19 UTC, PavelBoPavel commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    public void nullPointer(){
а в каком из исключений есть в названии глагол?

2021-08-06 08:20 UTC, PavelBoPavel commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    }
решил не писать дальше, пометка для себя.

2021-08-14 10:19 UTC, max-java requested changes
ptal

2021-08-14 10:19 UTC, max-java commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +        } else return values[values.length - 1];
In this particular case you'd better do 
```
public int riskyLastValueZero(int[] values) throws ArrayLastValueZeroException {
        if (values[values.length - 1] == 0) {
            throw new ArrayLastValueZeroException();
        }
 return values[values.length - 1];
```

2021-08-14 10:19 UTC, max-java commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +        } else return values[values.length - 1];
same as above

2021-08-14 10:19 UTC, max-java commented on homework/PavelBo/exceptions/knowingExceptions/src/main/java/com/tutrit/java/quickstart/service/Verification.java
> +    }
These methods looks like test cases, not business logic. 
And from your testes don't seem to be evident in with circumstances exceptions should be thrown. 
So you'd better move this into tests and from it as test cases;

Please, revise other  methods same way.

2021-08-17 11:24 UTC, closed without merging