Encoder task
javaGuruBY/jis8_homework pull request #58
Opened 2021-07-27 14:40 UTC by VasiliZas

2021-07-29 10:47 UTC, max-java requested changes
looks good, but please add quickstart project and run sonar

2021-07-30 10:21 UTC, KaydunovDenis approved these changes

2021-08-06 08:21 UTC, PavelBoPavel approved these changes

2021-08-14 09:45 UTC, max-java approved these changes
lgfm

2021-08-14 10:18 UTC, merged