add library work on bugs
javaGuruBY/jis8_homework pull request #70
Opened 2021-07-29 12:16 UTC by PavelBoPavel

2021-07-29 13:37 UTC, KaydunovDenis requested changes

2021-07-29 13:37 UTC, KaydunovDenis commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +    public Book findByBook(String bookName){
bookName or name Book? See you class Book.
I think these method need rename:
findByBook->findByNameBook

2021-07-29 13:37 UTC, KaydunovDenis commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +            ArrayList<Book> books = authorIsBooks.getValue();
Best practic use type "var"

2021-07-29 13:37 UTC, KaydunovDenis commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +            ArrayList<Book> books = new ArrayList<>();
Best practic use type "var"

2021-07-29 13:48 UTC, PavelBoPavel commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +            ArrayList<Book> books = authorIsBooks.getValue();
в данном случае не согласен. по значению справа от знака равно явно не понятен тип

2021-07-29 13:49 UTC, PavelBoPavel commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +            ArrayList<Book> books = new ArrayList<>();
согласен

2021-07-30 15:02 UTC, VasiliZas approved these changes

2021-08-14 10:43 UTC, max-java requested changes
ptal

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +            authorToBookNamesMap.put(book.getAuthorBook(), books);
```
if (authorToBookNamesMap.containsKey(book.getAuthorBook())) {
    authorBooks.getValue().add(book);
} else {
    authorToBookNamesMap.put(book.getAuthorBook(), List.of(books));
}
```

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +       }catch (NullPointerException e){
Best practices to write code the way that prevent NPE to be thrown, not catching it.

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +           authorToBookNamesMap.get(book.getAuthorBook()).remove(book);
At this point you should check if List under key is present.

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +           }
In practice, no need for this.

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/main/java/com/tutrit/java/quickstart/Library.java
> +    }
```
if (authorToBookNamesMap.containsKey(book.getAuthorBook()) {
    List<Books> books = authorToBookNamesMap.get(book.getAuthorBook());
    for (Book book : books) {
        if(book.getNameBook().equals(bookName)) {
            return book;
        }
    }
}
return null;
```

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/test/java/com/tutrit/java/quickstart/LibraryTest.java
> +        library.addBook(bookTolstoy2);
make it fabric method

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/test/java/com/tutrit/java/quickstart/LibraryTest.java
> +    Book bookTolstoy2;
This shouldn't bee here. that is test data should be provided by fabric

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/test/java/com/tutrit/java/quickstart/LibraryTest.java
> +        assertTrue(library.removeBook(bookChehov));
Make sure that book is no longer present in library

2021-08-14 10:43 UTC, max-java commented on homework/PavelBo/collections/library/src/test/java/com/tutrit/java/quickstart/LibraryTest.java
> +        extend.add(bookPuskin3);
You can create fabric method `getPushkinBooks()`
```
* {
return List.of(
    new Book("Pushkin", "pushka"), 
    new Book("Pushkin", "duska"), 
    new Book("Pushkin", "starushka"));
}
```

2021-08-17 11:39 UTC, closed without merging