add StringTokenazer_woekOnBugs
javaGuruBY/jis8_homework pull request #71
Opened 2021-07-29 12:48 UTC by PavelBoPavel

2021-08-05 11:09 UTC, KaydunovDenis requested changes

2021-08-06 08:29 UTC, PavelBoPavel commented on homework/PavelBo/collections/stringTokenizer/src/main/java/com/tutrit/java/quickstart/StringAnalyzer.java
> +        return Collections.list(new StringTokenizer(text, " йцукенгшщзхъфывапролджэячсмитьбюЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ")).stream()
в StringTokenazer регулярных выражений таких как в методе split() не нашел.

2021-08-07 14:04 UTC, max-java requested changes
ptal and let''s revise it once we reach the streams topic

2021-08-07 14:04 UTC, max-java commented on homework/PavelBo/collections/stringTokenizer/src/main/java/com/tutrit/java/quickstart/StringAnalyzer.java
> +                });
usually we don't mix streams with foreach 
also 
``` 
for {
    if {
        if {
        }
    }
}
``` 
is too complicated. I suggest you revise this and split into separate methods.

2021-08-07 14:04 UTC, max-java commented on homework/PavelBo/collections/stringTokenizer/src/test/java/com/tutrit/java/quickstart/StringAnalyzerTest.java
> +public class StringAnalyzerTest{
Nevertheless, it woks!

2021-11-25 17:13 UTC, closed without merging