JUnit homework
javaGuruBY/jis8_homework pull request #93
Opened 2021-08-20 20:17 UTC by VasiliZas

Создать сервис (UserService) и репозиторий (UserRepository) для сущности User и протестировать при помощи jUnit.

Основная сущность - User. Необходимые параметры:

идентификатор (id)
имя (name)
возраст (age)
Зависимости (dependencies):

У класса UserService должна быть зависимостьотUserRepository

Функциональные требования для класса UserService:

метод (addUser) для проверки пользователя и вызова метода сохранения пользователя в базу данных у репозитория.
Требования класса UserRepository. Необходимые параметры:

коллекция (users) для хранения пользователей. Используйте HashMap. В качестве ключа - id, в качестве значения - user.
Функциональные требования для класса UserRepository:

метод (save) для сохранения пользователя в коллекцию
Протестировать класс UserService при помощи Unit тестов. В качестве репозитория используйте MockUserRepository.
*Примечание: Так как при юнит тестировании не используется реальная база, необходимо создать mock. Создайте класс MockUserRepository. MockUserRepository наследуется от UserRepository.
Необходимые параметры для MockUserRepository:
триггер был ли вызван mock (isMockTriggered) - тип данных boolean.
Функциональные требования класса MockUserRepository:
Переопределенный метод save. В случае, если метод был вызван - менять состояние isMockTriggered на true.

В тестах проверить, что mock был вызван.

2021-08-20 20:20 UTC, VasiliZas commented
![JUnit](https://user-images.githubusercontent.com/78337920/130289288-5df0923c-7710-4d93-a9cb-07e4fa327d67.png)

2021-08-21 17:34 UTC, trump-ny approved these changes, later dismissed

2021-08-23 11:12 UTC, KaydunovDenis requested changes

2021-08-23 11:12 UTC, KaydunovDenis commented on homework/Vasili_Zasinets/JUnit/src/test/java/com/tutrit/java/quickstart/junit/UserServiceExceptionTest.java
> +public class UserServiceExceptionTest {
Я бы не разделял тесты для UserService на два отдельных тестовых класса, лично меня это ввело в заблуждение, что у тебя ещё есть  класс - UserServiceException

I would not separate tests for UserService into two separate test classes, personally it was misleading me that you have a class - UserServiceException

2021-08-23 11:12 UTC, KaydunovDenis commented on homework/Vasili_Zasinets/JUnit/src/test/java/com/tutrit/java/quickstart/junit/UserServiceExceptionTest.java
> +    public void addUserExceptoinIdTest() throws UserValidationException {
такое название тестового метода очень путает
this test method name is confusing

2021-08-23 11:12 UTC, KaydunovDenis commented on homework/Vasili_Zasinets/JUnit/src/test/java/com/tutrit/java/quickstart/junit/UserServiceExceptionTest.java
> +}
не хватает тестов на методы checkUserNotNull() и checkUserId()

2021-08-23 18:26 UTC, VasiliZas commented on homework/Vasili_Zasinets/JUnit/src/test/java/com/tutrit/java/quickstart/junit/UserServiceExceptionTest.java
> +}
я их тестирую в  тестах addUserExceptoinTest() и addUserExceptoinIdTest()

2021-08-23 18:27 UTC, VasiliZas commented on homework/Vasili_Zasinets/JUnit/src/test/java/com/tutrit/java/quickstart/junit/UserServiceExceptionTest.java
> +public class UserServiceExceptionTest {
ок

2021-08-24 14:35 UTC, max-java requested changes
I general ok, but we already can do much better. We'll practice 24.08 and then you'd better change this.

2021-08-24 14:35 UTC, max-java commented on homework/Vasili_Zasinets/JUnit/src/main/java/com/tutrit/java/quickstart/junit/UserService.java
> +    UserRepository userRepository = new UserRepository();
try to use DI here

2021-08-24 14:35 UTC, max-java commented on homework/Vasili_Zasinets/JUnit/src/test/java/com/tutrit/java/quickstart/junit/UserServiceTest.java
> +        this.userMockRepository = new HashMap<>();
don't this it will work. remind me - I'll show you on lection

2021-08-24 14:35 UTC, max-java commented on homework/Vasili_Zasinets/JUnit/src/main/java/com/tutrit/java/quickstart/junit/UserService.java
> +    }
migrate this to common Validation instance

2021-08-26 11:25 UTC, KaydunovDenis submitted a review, later dismissed

2021-08-27 15:41 UTC, trump-ny submitted a review, later dismissed

2021-09-03 07:34 UTC, KaydunovDenis approved these changes

2023-05-20 18:49 UTC, closed without merging